# Generated by Django 4.0.6 on 2022-07-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='files'),
        ),
    ]
