# Generated by Django 4.0.6 on 2022-07-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['pub_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['pub_date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='files'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='pub_date'),
        ),
    ]
